kind: pipeline
name: default

steps:
- name: publish
  image: plugins/ecr
  settings:
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    repo:
      from_secret: aws_ecr_repo
    registry:
      from_secret: aws_ecr_registry
    region:
      from_secret: aws_region
    tags:
      - latest
  when:
    branch:
      - master
    event:
      - push
- name: slack-beta
  image: plugins/slack
  settings:
    webhook:
      from_secret: continuous_deploy_slack_webhook
    template: >
      {{#success build.status}}
        Continuous deploy build on ${DRONE_BRANCH} {{build.link}} succeeded. :banana_dance:
      {{else}}
        大変！ Beta server build on ${DRONE_BRANCH} {{build.link}} failed!  Fix it <@boka>!
      {{/success}}
  when:
    branch:
      - master
    event:
      - push
    status:
      - success
      - failure
